### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by ajdelossantos** [ajdelossantos/Abstract#1]
- [x] Hosting

**Comment by ajdelossantos** [comment]
App has been pushed to Heroku successfully.

**Comment by ajdelossantos** [comment]
App pushed onto Heroku, encountered React components not rendering. Works fine on local machine. Will get help tomorrow.

**Comment by LochandQuay** [comment]
@ajdelossantos please comment the link here and update the link on your wiki

**Comment by ajdelossantos** [comment]
Deployed and ready.

http://abstract-io.herokuapp.com/#/

**Comment by LochandQuay** [comment]
Thanks!
