### ISSUE TITLE
PA Review: New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by ajdelossantos** [ajdelossantos/Abstract#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Componnents
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Guest/Demo login

**Comment by ajdelossantos** [comment]
Heroku push non-functional, though works on my local machine. Auth (as shown to Isak) is functional: login and logout, guest user enabled, styled closely to the original.

I'm requesting that the modal for login/logout be implemented at a later date. Due to the way the SessionForm was built, it would take major refactoring to implement a modal through React, which may cannibalize progress on other MVPs. Lack of modal does not impact functionality.

**Comment by LochandQuay** [comment]
@ajdelossantos 
Modals are not required for auth, so no worries. I can't check off any MVP until it is functional on Heroku though.

Also, if you're commenting on an issue for me, please tag me (I'll get a notification then).

**Comment by ajdelossantos** [comment]
Thank you for the feedback. Bug fixes for Heroku have been implemented and the MVP is ready for review.

**Comment by LochandQuay** [comment]
WOW! This looks really clean!

A couple very tiny comments:
- The error messages aren't very clear on the forms. They need to stand out a little more, either with styling or their location (or both).
- I generally prefer to have a demo login button on BOTH forms or to have it as it's own button on the nav bar, but I'll leave this as a decision for you.

**Comment by ajdelossantos** [comment]
DONE. I made an annotation that DEMO login is on the other page.

**Comment by LochandQuay** [comment]
Cool. I still want to talk to you about where the errors render and how they look, but this is good. :)
