### ISSUE TITLE
PA Review: Likes

### ISSUE THREAD

**Issue by ajdelossantos** [ajdelossantos/Abstract#7]
- [x] Backend: DB. model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by ajdelossantos** [comment]
Ready for review. I'll seed this along with the others tomorrow.

**Comment by LochandQuay** [comment]
@ajdelossantos 

- [ ] I would prefer the heart to be the part they click to like or unlike. But this works. 
- [ ] I'm not sure how I feel about the like section being before and after the story. I like how Medium does it (fixed along the side), but I'm not sure how you would implement that here. 
- [ ] As weird as it might be, I would prefer to be able to like a story on the story index item. At the very least, if I liked a story, I want the heart to be filled in on the index to indicate it's a story I liked.
- [ ] On the story index items, I think the liked area would be better in the lower right.
